### ISSUE TITLE
Respect "no-unused-import" Solhint rule

### ISSUE THREAD

**Issue by PaulRBerg** [PraneshASP/vscode-solidity-inspector#17]
See https://github.com/sablier-labs/v2-core/blob/2beb466bcbd0769479b1fc257ab11ba7c959d60d/src/types/Tokens.sol

Screenshot:

<img width="400" alt="SCR-20230707-mdqx" src="https://github.com/PraneshASP/vscode-solidity-inspector/assets/8782666/0aa6bc30-d482-4755-9ae6-e8504f7b2cfc">

**Comment by PraneshASP** [comment]
As mentioned in the README, this tool only tracks unused imports for the active or current file. Agreed that this limitation should be addressed :+1:
