### ISSUE TITLE
Ignore highlighting unused imports when commented out

### ISSUE THREAD

**Issue by 0xMySt1c** [PraneshASP/vscode-solidity-inspector#19]
It would be nice to ignore highlighting unused imports when the import is commented because comments are already greyed out in vscode.

**Comment by PraneshASP** [comment]
Good suggestion. Will look into it this weekend. Thanks!

**Comment by PraneshASP** [comment]
The fix has been shipped in the latest release. Can you check please?

**Comment by PraneshASP** [comment]
Tested on my end. Closing this issue for now. Feel free to re-open if its still not working for you.
