### ISSUE TITLE
Allow the name of the tree file to not have a file extension

### ISSUE THREAD

**Issue by PaulRBerg** [PraneshASP/vscode-solidity-inspector#29]
Installing this extension and using it on a tree like this:

```tree
GivenWhenTest
├── given value is less than 100
│  └── it should revert
└── given value is not less than 100
   ├── when x is false
   │  └── it should revert
   └── when x is true
      └── it should return x
```

Produces the following syntax error:

> Should be a valid test name (ending with .t.sol)

This is unexpected behavior. As discussed in https://github.com/alexfertel/bulloak/issues/3, the BTT format allows the name at the top of the tree file to be simply the contract name (no extension).

For more examples, see my repo https://github.com/PaulRBerg/btt-examples.

**Comment by PraneshASP** [comment]
Thanks for reporting! Will look into it soon.

**Comment by PraneshASP** [comment]
The fix has been shipped in the latest release. Can you check please?

**Comment by PaulRBerg** [comment]
works! thanks
