### ISSUE TITLE
False positive unused import error for libraries

### ISSUE THREAD

**Issue by PaulRBerg** [PraneshASP/vscode-solidity-inspector#31]
Imported libraries show up as unused even if they are used multiple times.

Reproducible example here:

https://github.com/sablier-labs/v2-core/blob/ba827e19f52c905fd5d5478d0b7dda10c3ef2800/src/libraries/Helpers.sol#L6

**Comment by PraneshASP** [comment]
Thanks for reporting! Will look into it soon.

**Comment by PraneshASP** [comment]
The fix has been shipped in the latest release. Can you check please? @PaulRBerg

**Comment by PaulRBerg** [comment]
Yep, works now, thanks Pranesh!
