### ISSUE TITLE
import completion to handle pre-existing {}

### ISSUE THREAD

**Issue by devtooligan** [PraneshASP/vscode-solidity-inspector#50]
The auto import completion is a feature I use almost every day. Thank you.

One small thing that gets me though is I often start typing:

`import {` 

and by default, my vscode adds the closing `}` at the end of my selection, so for example:

`import {SSTORE}`

Then your extension kicks in and I see what I'm looking for and choose it, but it will insert inside the {} for:

`import {{ SSTORE2 } from "lib/solmate/src/utils/SSTORE2.sol";}`

And I have to manually delete the extra {}

Just a small thing, I know. I guess I should get in the habit of typing `import SSTORE` without the { but it's like muscle memory or something lol.

Is there any way to handle it gracefully if there is already braces?

Anyways, thanks so much for this extension 🙏

**Comment by PraneshASP** [comment]
Thanks for raising this. This will be fixed in the upcoming release (1.4.1)

### Before:


https://github.com/user-attachments/assets/dc4ada16-3621-44f4-ac4d-36ecfb6e1f1b


### After:

https://github.com/user-attachments/assets/f62a50fe-17c0-47e5-b9b7-2eed7356b97b
